# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wrc/dev/W-DesktopCountdown/Scripts/../UISource/countdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Countdown(object):
    def setupUi(self, Countdown):
        Countdown.setObjectName("Countdown")
        Countdown.resize(579, 278)
        self.verticalLayout = QtWidgets.QVBoxLayout(Countdown)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Countdown)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Countdown)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Countdown)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(Countdown)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Countdown)
        QtCore.QMetaObject.connectSlotsByName(Countdown)

    def retranslateUi(self, Countdown):
        _translate = QtCore.QCoreApplication.translate
        Countdown.setWindowTitle(_translate("Countdown", "Form"))
        self.label_2.setText(_translate("Countdown", "距离{}还有{}"))
        self.label_3.setText(_translate("Countdown", "{}"))
        self.label.setText(_translate("Countdown", "{}"))
