# This is a basic workflows to help you get started with Actions

name: Build to EXE

# Controls when the workflows will run
on:
  # Triggers the workflows on push or pull request events but only for the master branch
  create:
  
  workflow_dispatch:

# A workflows run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflows contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.9'

      # Runs a single command using the runners shell
      - name: Setup python packages
        run: |
            pip install -r requirements.txt
            pip install pyinstaller
      
      - name: List all files
        run: dir
      
      # Start building
      - name: Building EXE
        run: |
          cd Scripts
          cmd /c Build.bat
      
      - name: Update to release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ./dist/*
          draft: true

